# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSums_cpp <- function(A) {
    .Call(`_dFCHMM_colSums_cpp`, A)
}

rowSums_cpp <- function(A) {
    .Call(`_dFCHMM_rowSums_cpp`, A)
}

logvec_c <- function(x) {
    .Call(`_dFCHMM_logvec_c`, x)
}

factorial_cpp <- function(n) {
    .Call(`_dFCHMM_factorial_cpp`, n)
}

covmat_c <- function(Xt, mu, u) {
    .Call(`_dFCHMM_covmat_c`, Xt, mu, u)
}

standardize_rows_cpp <- function(A) {
    .Call(`_dFCHMM_standardize_rows_cpp`, A)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_dFCHMM_dmvnrm_arma`, x, mean, sigma, logd)
}

eye_cpp <- function(P) {
    .Call(`_dFCHMM_eye_cpp`, P)
}

logsumexp_cpp <- function(X) {
    .Call(`_dFCHMM_logsumexp_cpp`, X)
}

get_emission_distribution <- function(Xt, u_all, m, SampCov, mu_hat_next, Sigma_hat_next, Omega_hat_next, penalty) {
    invisible(.Call(`_dFCHMM_get_emission_distribution`, Xt, u_all, m, SampCov, mu_hat_next, Sigma_hat_next, Omega_hat_next, penalty))
}

forward_backward_cpp <- function(Xt, B, mu, Sigma, delta) {
    .Call(`_dFCHMM_forward_backward_cpp`, Xt, B, mu, Sigma, delta)
}

hmm_cpp <- function(Xt, num_states, Sigma_init, maxiter = 10000L, tol = 1e-4, verbose = 1L) {
    .Call(`_dFCHMM_hmm_cpp`, Xt, num_states, Sigma_init, maxiter, tol, verbose)
}

